Chapter 3 - Numpy

In [15]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 16.7 ms, sys: 4.18 ms, total: 20.9 ms
Wall time: 55.1 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 513 ms, sys: 108 ms, total: 621 ms
Wall time: 621 ms


In [6]:
data = np.random.randn(2, 3)
data

array([[-0.321737  ,  1.26049885,  1.09242229],
       [ 1.48705783, -0.08348022,  1.88801643]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

In [10]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
arr1.ndim

1

In [12]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
arr1.astype(np.float64)

array([6. , 7.5, 8. , 0. , 1. ])

In [17]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [18]:
 arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [26]:
arr[1,0:2]

array([4., 5.])

In [31]:
arr[arr > 4]

array([5., 6.])

In [43]:
data = np.random.randn(7, 4)
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data

array([[-0.56235458, -1.90345763,  0.20260446,  0.19100398],
       [ 1.34392881,  0.88938373, -0.34801115,  0.30058804],
       [-0.00683412, -2.07036565,  0.16251637, -0.60974073],
       [ 0.34412488, -0.29938525, -0.6909864 ,  1.6340325 ],
       [ 0.53588781,  0.26913376,  0.71681519, -1.39845531],
       [ 0.85451036,  2.07778033,  0.81644848,  1.85132657],
       [-0.68378233, -0.85694144,  0.93803275, -0.01130445]])

In [44]:
data[~(names == 'Bob')]

array([[ 1.34392881,  0.88938373, -0.34801115,  0.30058804],
       [-0.00683412, -2.07036565,  0.16251637, -0.60974073],
       [ 0.53588781,  0.26913376,  0.71681519, -1.39845531],
       [ 0.85451036,  2.07778033,  0.81644848,  1.85132657],
       [-0.68378233, -0.85694144,  0.93803275, -0.01130445]])

In [45]:
((names == 'Bob') | (names == 'Will')) & (names == 'Joe')

array([False, False, False, False, False, False, False])

In [46]:
data[[1,0]]

array([[ 1.34392881,  0.88938373, -0.34801115,  0.30058804],
       [-0.56235458, -1.90345763,  0.20260446,  0.19100398]])

In [50]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [51]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [52]:
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [54]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [3]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [7]:
np.save("data/array", xarr)

In [9]:
np.load('data/array.npy')

array([1.1, 1.2, 1.3, 1.4, 1.5])

In [10]:
np.savez('array_archive.npz', a=xarr, b=yarr)

In [11]:
arch = np.load('array_archive.npz')
arch['a']

array([1.1, 1.2, 1.3, 1.4, 1.5])

In [12]:
arch['b']

array([2.1, 2.2, 2.3, 2.4, 2.5])

In [13]:
samples = np.random.normal(size=(4, 4))
samples

array([[-0.21700169, -0.08693141,  1.86358188,  0.62823718],
       [ 0.47544756, -0.13797243,  1.41991361, -1.19616257],
       [ 0.2543346 ,  1.92662248,  1.79190755,  1.2894031 ],
       [-0.68163703, -0.47801151,  0.18557295, -0.80729418]])