Chapter 3 - Numpy

In [8]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 16.7 ms, sys: 4.18 ms, total: 20.9 ms
Wall time: 55.1 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 513 ms, sys: 108 ms, total: 621 ms
Wall time: 621 ms


In [6]:
data = np.random.randn(2, 3)
data

array([[-0.321737  ,  1.26049885,  1.09242229],
       [ 1.48705783, -0.08348022,  1.88801643]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

In [10]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
arr1.ndim

1

In [12]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
arr1.astype(np.float64)

array([6. , 7.5, 8. , 0. , 1. ])

In [17]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [18]:
 arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [26]:
arr[1,0:2]

array([4., 5.])

In [31]:
arr[arr > 4]

array([5., 6.])

In [43]:
data = np.random.randn(7, 4)
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data

array([[-0.56235458, -1.90345763,  0.20260446,  0.19100398],
       [ 1.34392881,  0.88938373, -0.34801115,  0.30058804],
       [-0.00683412, -2.07036565,  0.16251637, -0.60974073],
       [ 0.34412488, -0.29938525, -0.6909864 ,  1.6340325 ],
       [ 0.53588781,  0.26913376,  0.71681519, -1.39845531],
       [ 0.85451036,  2.07778033,  0.81644848,  1.85132657],
       [-0.68378233, -0.85694144,  0.93803275, -0.01130445]])

In [44]:
data[~(names == 'Bob')]

array([[ 1.34392881,  0.88938373, -0.34801115,  0.30058804],
       [-0.00683412, -2.07036565,  0.16251637, -0.60974073],
       [ 0.53588781,  0.26913376,  0.71681519, -1.39845531],
       [ 0.85451036,  2.07778033,  0.81644848,  1.85132657],
       [-0.68378233, -0.85694144,  0.93803275, -0.01130445]])

In [45]:
((names == 'Bob') | (names == 'Will')) & (names == 'Joe')

array([False, False, False, False, False, False, False])

In [46]:
data[[1,0]]

array([[ 1.34392881,  0.88938373, -0.34801115,  0.30058804],
       [-0.56235458, -1.90345763,  0.20260446,  0.19100398]])

In [50]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [51]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [52]:
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [54]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [3]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [7]:
np.save("data/array", xarr)

In [9]:
np.load('data/array.npy')

array([1.1, 1.2, 1.3, 1.4, 1.5])

In [10]:
np.savez('array_archive.npz', a=xarr, b=yarr)

In [11]:
arch = np.load('array_archive.npz')
arch['a']

array([1.1, 1.2, 1.3, 1.4, 1.5])

In [12]:
arch['b']

array([2.1, 2.2, 2.3, 2.4, 2.5])

In [13]:
samples = np.random.normal(size=(4, 4))
samples

array([[-0.21700169, -0.08693141,  1.86358188,  0.62823718],
       [ 0.47544756, -0.13797243,  1.41991361, -1.19616257],
       [ 0.2543346 ,  1.92662248,  1.79190755,  1.2894031 ],
       [-0.68163703, -0.47801151,  0.18557295, -0.80729418]])

Chapter 4 - DataFrame

In [6]:
import numpy as np
import pandas as pd
df1 = pd.Series(range(3), index = ['a', 'b', 'c'])
ind = df1.index
ind

Index(['a', 'b', 'c'], dtype='object')

In [10]:
labels = pd.Index(np.arange(5,14,3))
labels

Int64Index([5, 8, 11], dtype='int64')

In [11]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

5     1.5
8    -2.5
11    0.0
dtype: float64

In [12]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'])

In [13]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [20]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [24]:
frame2.drop(['Ohio'], axis = 1)

Texas  California
a    1.0         2.0
b    NaN         NaN
c    4.0         5.0
d    7.0         8.0

In [25]:
frame2.drop(["a", "b"])

Ohio  Texas  California
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [30]:
# to get data by column name and index label
frame2.loc[['a','c'],['Ohio','California']]

Ohio  California
a   0.0         2.0
c   3.0         5.0

In [33]:
# to get data by giving position column or row
frame2.iloc[[0,2],[0,2]]

Ohio  California
a   0.0         2.0
c   3.0         5.0

In [34]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon'])

df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [7]:
import pandas_datareader.data as web

In [8]:
all_data = {ticker: web.get_data_yahoo(ticker) for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

price = pd.DataFrame({ticker: data['Adj Close'] for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume'] for ticker, data in all_data.items()})

In [9]:
returns = price.pct_change()

In [10]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2019-12-16  0.017118 -0.000596  0.006471  0.009897
2019-12-17  0.001965  0.000671 -0.005401 -0.004445
2019-12-18 -0.002389  0.001416 -0.002069 -0.001845
2019-12-19  0.001001  0.001116  0.008681  0.002528
2019-12-20 -0.000928  0.009661  0.009408 -0.003429

In [11]:
returns['MSFT'].corr(returns['IBM'])

0.4850171945435799

In [12]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.399422  0.573415  0.521865
IBM   0.399422  1.000000  0.485017  0.410497
MSFT  0.573415  0.485017  1.000000  0.658951
GOOG  0.521865  0.410497  0.658951  1.000000

In [1]:
import json
obj = """
{"name": "Wes",
"places_lived": ["United States", "Spain", "Germany"],
"pet": null,
"siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
{"name": "Katie", "age": 38,
"pets": ["Sixes", "Stache", "Cisco"]}]
}
"""

In [4]:
result = json.loads(obj)
result

{'name': 'Wes',
 'places_lived': ['United States', 'Spain', 'Germany'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
  {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]}

In [6]:
!conda install lxml
!pip install beautifulsoup4 html5lib

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.7.12
  latest version: 4.8.0

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.

     |████████████████████████████████| 102kB 91kB/s ta 0:00:011
     |████████████████████████████████| 122kB 120kB/s eta 0:00:01


In [15]:
tables = pd.read_html('http://www.ffiec.gov/census/report.aspx?year=2011&state=01&report=demographic&msa=11500')


In [16]:
len(tables)

7

In [25]:
tables[6].head()

County Code  Tract Code Tract Income Level  \
0           15         1.0           Moderate   
1           15         2.0             Middle   
2           15         3.0           Moderate   
3           15         4.0           Moderate   
4           15         5.0                Low   

  Distressed or Under -served Tract  Tract Median Family Income %  \
0                                No                         74.23   
1                                No                         86.40   
2                                No                         59.27   
3                                No                         76.24   
4                                No                         40.54   

  2011 HUD Est. MSA/MD non-MSA/MD Median Family Income  \
0                                            $51,500     
1                                            $51,500     
2                                            $51,500     
3                                            $51,500     
4                                            $51,500     

  2011 Est. Tract Median Family Income 2000 Tract Median Family Income  \
0                              $38,228                         $29,615   
1                              $44,496                         $34,468   
2                              $30,524                         $23,644   
3                              $39,264                         $30,417   
4                              $20,878                         $16,172   

   Tract Population  Tract Minority %  Minority Population  \
0              2279             45.77                 1043   
1              3084             42.44                 1309   
2              3545             78.87                 2796   
3              2777             59.42                 1650   
4              2372             93.55                 2219   

   Owner Occupied Units  1- to 4- Family Units  
0                   431                    894  
1                   881                   1543  
2                   637                   1562  
3                   908                   1335  
4                   597                   1306

In [29]:
tables[6]['Tract Income Level'].value_counts()

Middle      14
Moderate     6
Upper        5
Low          3
Name: Tract Income Level, dtype: int64

In [31]:
from numpy import nan as NA
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],[NA, NA, NA], [NA, 6.5, 3.]])

In [32]:
data.dropna(how="all", axis = 1)

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [35]:
df = pd.DataFrame(np.random.randn(7, 3))
df

0         1         2
0 -0.286147  1.447727  0.013059
1 -0.084053  0.433279 -1.626502
2  3.906515 -0.204119  0.426389
3 -0.359298  1.616905  0.145675
4  2.078140 -0.252865  0.217629
5  0.932220  0.107232 -0.591519
6 -1.056407  1.062329 -0.736466

In [37]:
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df

0         1         2
0 -0.286147       NaN       NaN
1 -0.084053       NaN       NaN
2  3.906515       NaN  0.426389
3 -0.359298       NaN  0.145675
4  2.078140 -0.252865  0.217629
5  0.932220  0.107232 -0.591519
6 -1.056407  1.062329 -0.736466

In [39]:
# thresh stops from droping rows which have atleast n number of observations
df.dropna(thresh=2)

0         1         2
2  3.906515       NaN  0.426389
3 -0.359298       NaN  0.145675
4  2.078140 -0.252865  0.217629
5  0.932220  0.107232 -0.591519
6 -1.056407  1.062329 -0.736466

In [41]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -0.286147  0.500000  0.000000
1 -0.084053  0.500000  0.000000
2  3.906515  0.500000  0.426389
3 -0.359298  0.500000  0.145675
4  2.078140 -0.252865  0.217629
5  0.932220  0.107232 -0.591519
6 -1.056407  1.062329 -0.736466

In [44]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],'k2': [1, 1, 2, 3, 3, 4, 4]})
data.duplicated(['k1'])

0    False
1    False
2     True
3     True
4     True
5     True
6     True
dtype: bool

In [45]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
6  two   4

In [54]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
'Pastrami', 'corned beef', 'Bacon',
'pastrami', 'honey ham', 'nova lox'],
'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [49]:
#converting all food names to lower
lowercased_food = data['food'].str.lower()

In [55]:
# mapping the food type to the animal 
meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
}

#data['animal'] = lowercased_food.map(meat_to_animal)

data['food'].map(lambda x: meat_to_animal[x.lower()])

data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [58]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [63]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [64]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [66]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
cats2 = pd.cut(ages, bins, labels=group_names)

In [67]:
pd.value_counts(cats2)

Youth         5
MiddleAged    3
YoungAdult    3
Senior        1
dtype: int64

In [72]:
data = np.random.rand(20)
pd.cut(data, 4, precision=2).value_counts()

(0.013, 0.25]    8
(0.25, 0.49]     3
(0.49, 0.73]     6
(0.73, 0.97]     3
dtype: int64

In [74]:
data = np.random.randn(1000) # Normally distributed
cats = pd.qcut(data, 4) # Cut into quartiles
cats.value_counts()

(-2.746, -0.717]    250
(-0.717, 0.0444]    250
(0.0444, 0.704]     250
(0.704, 3.066]      250
dtype: int64

In [75]:
data = np.random.randn(1000) # Normally distributed
cats = pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])
cats.value_counts()

(-3.471, -1.224]    100
(-1.224, 0.0617]    400
(0.0617, 1.215]     400
(1.215, 3.357]      100
dtype: int64

Detecting and Filtering Outliers

In [76]:
dta = pd.DataFrame(np.random.randn(1000, 4))
dta.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.037241    -0.002207    -0.052676     0.018242
std       0.987771     1.013563     0.975578     1.043918
min      -3.632113    -3.473459    -3.022037    -2.983877
25%      -0.743620    -0.716847    -0.685403    -0.691926
50%      -0.005108    -0.005066    -0.091826     0.006080
75%       0.648906     0.713855     0.605818     0.690923
max       3.550165     2.839151     2.893272     3.148073

In [80]:
# Suppose you wanted to find values in one of the columns exceeding 3 in absolute
dta[2][np.abs(dta[2]) > 3]

261   -3.022037
Name: 2, dtype: float64

In [81]:
dta[(np.abs(dta) > 3).any(1)]

0         1         2         3
109 -3.632113 -0.311084  0.733869 -0.971696
237  3.367949  0.297433  1.480575 -0.797415
261  0.147361 -1.877017 -3.022037  1.636909
663  0.170884 -3.473459  0.592760  0.106769
771  0.630118  0.865658  1.096657  3.032869
818 -0.746975 -1.213159  0.480218  3.148073
906  3.550165  0.083451  2.259897 -0.200862