In [2]:
import numpy as np

In [3]:
arr = np.arange(1,37).reshape(6,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

# slicing

In [13]:
# array[row range, column range]
arr[0:3,1:4]

array([[ 2,  3,  4],
       [ 8,  9, 10],
       [14, 15, 16]])

In [14]:
# steps in slicing
arr[:,0:6:2]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

# indexing

In [17]:
d3 = np.arange(50).reshape(2,5,5)
d3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [28]:
d3[0][3][2]

17

In [29]:
d3[0][3][1:4]

array([16, 17, 18])

In [49]:
d3[1,:,1:2]

array([[26],
       [31],
       [36],
       [41],
       [46]])

In [50]:
d3[1][:,1:2]

array([[26],
       [31],
       [36],
       [41],
       [46]])

# boolean indexing

In [51]:
data = np.arange(64).reshape(8,8)

In [52]:
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [80]:
boolarr = np.array([True, True, False, False, False, False, True, True], dtype ="bool")
boolarr

array([ True,  True, False, False, False, False,  True,  True])

In [65]:
data[data % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62])

In [68]:
data[boolarr] # this is also a fancy indexing, define below

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

# fancy indexing

In [79]:
# i passed a list in place of row and the program picked all the rows using list elements as row id
data[[2,1,6]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [73]:
# in numpy we use & instead of and for logical operations
conitional_array = (data % 2 == 0) & (data % 3 == 0)
data[conitional_array]

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60])

In [74]:
# in numpy we use | instead of and for logical operations
conitional_array = (data % 2 == 0) | (data % 3 == 0)
data[conitional_array]

array([ 0,  2,  3,  4,  6,  8,  9, 10, 12, 14, 15, 16, 18, 20, 21, 22, 24,
       26, 27, 28, 30, 32, 33, 34, 36, 38, 39, 40, 42, 44, 45, 46, 48, 50,
       51, 52, 54, 56, 57, 58, 60, 62, 63])

In [87]:
name = np.array(["syed azfar", "ali"])
name

array(['syed azfar', 'ali'], dtype='<U10')

In [84]:
name2 = np.array([1,2,3])
name2

array([1, 2, 3])

In [92]:
arr2 = np.empty((8,4))
for i in range(8):
    arr2[i] = i
arr2

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [93]:
arr2[[3,2,5],1:3]

array([[3., 3.],
       [2., 2.],
       [5., 5.]])

In [95]:
arr3 = np.arange(16).reshape(4,4)
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [97]:
arr3[[2,0],[1,2]]
# the above command picks elements based on following (2,1), (0,2)

array([9, 2])

In [102]:
arr3[[1,0]][:,[0,3]]
# the above command picks elements based on following 
# => 1(0,3), 0(0,3)
# => [(1,0), (1,3)], [(0,0), (0,3)]

array([[4, 7],
       [0, 3]])

# Transposing Arrays and Swapping Axes

In [109]:
arr4 = np.arange(15).reshape(3,5)
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [124]:
# transposing an array
arr4.T
# same result with arr4.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [114]:
# inner matrix product
np.dot(arr4.T, arr4)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [125]:
# tooo much to handle
# multi dimensional array
arr5 = np.arange(16).reshape((2,2,4))
arr5

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [126]:
arr5.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [127]:
arr4.swapaxes(1,0)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

# Universal Functions: Fast Element-wise Array Functions


In [139]:
arr6 = np.arange(10)
arr7 = np.arange(10,20)
arr6, arr7

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]))

In [129]:
np.sqrt(arr6)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [150]:
arr8 = np.array([1,2.5,-10])
np.modf(arr8) # returns remainder and whole_part 

(array([ 0. ,  0.5, -0. ]), array([  1.,   2., -10.]))

In [141]:
np.maximum(arr6,arr7) # compares each element of arr6 with arr7 for maximum

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [148]:
np.abs(arr6)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [151]:
np.sign(arr8)

array([ 1.,  1., -1.])

In [153]:
np.ceil(arr8)

array([  1.,   3., -10.])

In [154]:
np.floor(arr8)

array([  1.,   2., -10.])

In [155]:
np.rint(arr8) # to round each element of an array

array([  1.,   2., -10.])

# reshape orders

In [165]:
arr9 = np.arange(15).reshape(3,5)
arr9

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [163]:
# to re arrange an array to 1 dimensional
arr9.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [172]:
# this function works by passing reference so original array is modified
arr9.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [176]:
arr10 = np.array([[1, 2, 3], [4, 5, 6]])
arr11 = np.array([[7, 8, 9], [10, 11, 12]])


In [178]:
np.concatenate([arr10,arr11], axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])